wandb_version: 1

mode:
  desc: null
  value: train
verbose:
  desc: null
  value: true
video_type:
  desc: null
  value: tvsum
input_size:
  desc: null
  value: 1024
hidden_size:
  desc: null
  value: 256
nhead:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 2
dim_feedforward:
  desc: null
  value: null
regularization_factor:
  desc: null
  value: 0.15
n_epochs:
  desc: null
  value: 100
clip:
  desc: null
  value: 5.0
lr:
  desc: null
  value: 2.0e-05
discriminator_lr:
  desc: null
  value: 1.0e-05
split_index:
  desc: null
  value: 1
wandb_project:
  desc: null
  value: attentive-sum-gan
wandb_run_prefix:
  desc: null
  value: ''
log_dir:
  desc: null
  value: ../output/attentive/tvsum/logs/split1
score_dir:
  desc: null
  value: ../output/attentive/tvsum/results/split1
save_dir:
  desc: null
  value: ../output/attentive/tvsum/models/split1
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700587538.262052
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 2
      - 5
